services:
  caddy:
    image: caddy:2-alpine
    container_name: shorten-caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "443:443/udp"  # For HTTP/3
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    networks:
      - shorten-network
    depends_on:
      - frontend
      - app

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "devuser", "-d", "devdb"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - shorten-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:9001/minio/health/live"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - shorten-network

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      set -e;
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/audio --ignore-existing;
      /usr/bin/mc mb minio/speech-mark --ignore-existing;
      /usr/bin/mc mb minio/llm --ignore-existing;
      /usr/bin/mc mb minio/cleaned --ignore-existing;
      echo 'Buckets created successfully on MinIO server.';
      "
    networks:
      - shorten-network

  loki:
    image: grafana/loki:2.9.8
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - shorten-network

  app:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "2112:2112"
    environment:
      LOKI_URL: http://loki:3100
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
    depends_on:
      loki:
        condition: service_started
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      createbuckets:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-U", "devuser"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - shorten-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    volumes:
      - ./fe/.env:/app/.env
    networks:
      - shorten-network

volumes:
  postgres_data:
  minio_data:
  caddy_data:
  caddy_config:

networks:
  shorten-network:
    driver: bridge