import React from 'react';
import Link from 'next/link';
import MainHeader from '@/components/MainHeader';
import Footer from '@/components/Footer';

export default function Terms() {
  const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'contact@shorten.io';

  return (
    <div className="bg-[#1e1e1e] min-h-screen flex flex-col">
      <MainHeader />
      <div className="flex-1 px-6 py-20 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h1 className="text-[#f2bb4b] text-4xl font-semibold tracking-tight sm:text-5xl mb-4">
              Terms of Service
            </h1>
            <p className="text-white text-sm sm:text-base">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>

          <div className="prose prose-invert max-w-none">
            <div className="bg-gray-800/50 rounded-lg p-6 sm:p-8 space-y-6 text-white">
              
              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
                <p className="text-gray-300 leading-relaxed">
                  By accessing and using Shorten ("the Service"), you accept and agree to be bound by 
                  these Terms of Service. If you do not agree to these terms, please do not use our Service.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">2. Description of Service</h2>
                <p className="text-gray-300 leading-relaxed">
                  Shorten is a free web service that:
                </p>
                <ul className="list-disc list-inside ml-4 mt-2 space-y-2 text-gray-300">
                  <li>Summarizes content from web pages</li>
                  <li>Generates text-to-speech audio for the summaries</li>
                </ul>
                <p className="text-gray-300 leading-relaxed mt-4">
                  The Service is provided "as is" without warranties of any kind.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">3. Use of Service</h2>
                <div className="space-y-4 text-gray-300">
                  <div>
                    <h3 className="text-white font-medium mb-2">3.1 Permitted Use</h3>
                    <p className="leading-relaxed">
                      You may use the Service for lawful purposes only. You agree not to use the Service:
                    </p>
                    <ul className="list-disc list-inside ml-4 mt-2 space-y-1">
                      <li>To violate any applicable laws or regulations</li>
                      <li>To infringe upon the rights of others</li>
                      <li>To transmit harmful, offensive, or illegal content</li>
                      <li>To attempt to gain unauthorized access to our systems</li>
                      <li>To interfere with or disrupt the Service</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-white font-medium mb-2">3.2 Content Responsibility</h3>
                    <p className="leading-relaxed">
                      You are solely responsible for the URLs you submit to the Service. We do not 
                      endorse, support, or verify the accuracy of content from third-party websites. 
                      The summaries generated are for informational purposes only.
                    </p>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">4. Intellectual Property</h2>
                <div className="space-y-4 text-gray-300">
                  <div>
                    <h3 className="text-white font-medium mb-2">4.1 Our Content</h3>
                    <p className="leading-relaxed">
                      All content, features, and functionality of the Service, including but not limited 
                      to text, graphics, logos, and software, are owned by Shorten and are protected 
                      by copyright, trademark, and other intellectual property laws.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-white font-medium mb-2">4.2 Third-Party Content</h3>
                    <p className="leading-relaxed">
                      Summaries generated by the Service are based on third-party content. We do not 
                      claim ownership of the original content. You are responsible for respecting the 
                      intellectual property rights of third-party content owners.
                    </p>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">5. Service Availability</h2>
                <p className="text-gray-300 leading-relaxed">
                  We strive to provide reliable service but do not guarantee uninterrupted or error-free 
                  operation. The Service may be temporarily unavailable due to maintenance, updates, or 
                  unforeseen circumstances. We reserve the right to modify, suspend, or discontinue the 
                  Service at any time without notice.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">6. Limitation of Liability</h2>
                <p className="text-gray-300 leading-relaxed">
                  To the fullest extent permitted by law, Shorten shall not be liable for any indirect, 
                  incidental, special, consequential, or punitive damages, or any loss of profits or 
                  revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, 
                  or other intangible losses resulting from your use of the Service.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">7. Disclaimer of Warranties</h2>
                <p className="text-gray-300 leading-relaxed">
                  The Service is provided "as is" and "as available" without any warranties, express or 
                  implied. We do not warrant that the Service will be accurate, reliable, error-free, or 
                  uninterrupted. Summaries generated by the Service are for informational purposes only 
                  and should not be relied upon as definitive or complete.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">8. Data and Privacy</h2>
                <p className="text-gray-300 leading-relaxed">
                  Your use of the Service is subject to our Privacy Policy. By using the Service, you 
                  consent to the collection and use of information as described in the Privacy Policy. 
                  We temporarily store URLs, summaries, and related data for up to 7 days for analytics 
                  purposes only.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">9. Indemnification</h2>
                <p className="text-gray-300 leading-relaxed">
                  You agree to indemnify and hold harmless Shorten, its officers, directors, employees, 
                  and agents from any claims, damages, losses, liabilities, and expenses (including 
                  legal fees) arising out of or relating to your use of the Service or violation of 
                  these Terms.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">10. Modifications to Terms</h2>
                <p className="text-gray-300 leading-relaxed">
                  We reserve the right to modify these Terms of Service at any time. We will notify users 
                  of any material changes by updating the "Last updated" date. Your continued use of the 
                  Service after such modifications constitutes acceptance of the updated Terms.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">11. Governing Law</h2>
                <p className="text-gray-300 leading-relaxed">
                  These Terms of Service shall be governed by and construed in accordance with the laws 
                  of India, without regard to its conflict of law provisions. Any disputes arising from 
                  these Terms or your use of the Service shall be subject to the exclusive jurisdiction 
                  of the courts of India.
                </p>
              </section>

              <section>
                <h2 className="text-[#f2bb4b] text-2xl font-semibold mb-4">12. Severability</h2>
                <p className="text-gray-300 leading-relaxed">
                  If any provision of these Terms is found to be unenforceable or invalid, that provision 
                  shall be limited or eliminated to the minimum extent necessary, and the remaining 
                  provisions shall remain in full force and effect.
                </p>
              </section>

            </div>
          </div>

          <div className="text-center mt-12">
            <Link 
              href="/"
              className="text-[#f2bb4b] hover:text-yellow-400 text-sm font-medium"
            >
              ← Back to Home
            </Link>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}